---
roles:
  pe-puppet-master:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    providers:
      - type: virtualbox
        linked_clone: true
        customize:
          - [modifyvm, !ruby/sym id, '--memory', 2048]
    provisioners:
      - {type: hosts, sync_hosts: true}
      - {type: pe_bootstrap, role: !ruby/sym master}

  pe-puppet-agent:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    providers:
      - type: virtualbox
        linked_clone: true
    provisioners:
      - {type: hosts, sync_hosts: true}
      - {type: pe_agent, master: master}
